import json
import shutil
import os

html = '''
<!DOCTYPE html>
<html>
<head>
    <title>EngWeb2023</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
</head>
<body>
'''

template = html

file = open("Dados/mapa.json", "r", encoding="utf-8").read()

html_folder = 'html'
if os.path.exists(html_folder):
    shutil.rmtree(html_folder)
os.makedirs(html_folder)

content = json.loads(file)

html += "<h1>Cidades</h1><ul>"

# Faz o mapping do id da cidade para o seu nome
id_to_nome = {}
for elem in content["cidades"]:
    id_to_nome[elem['id']] = elem['nome']

# Carrega as ligações para memória
ligacoes = {}
for elem in content["ligações"]:
    if elem['origem'] not in ligacoes:
        ligacoes[elem['origem']] = []
    ligacoes[elem['origem']].append((elem['destino'], id_to_nome[elem['destino']]))

listaCidades = []
for elem in content["cidades"]:
    listaCidades.append((elem['id'], elem['nome']))

    templateCidade = template
    templateCidade += f'''
        <div class="w3-card-4">
            <header class="w3-container w3-teal">
                <h3>{elem['nome']}</h3>
            </header>
            <div class="w3-container">
    '''
    templateCidade += f"<h4>{elem['distrito']}</h4>"
    templateCidade += f"<p><b>População: </b>{elem['populaÃ§Ã£o']}</p>"
    templateCidade += f"<p><b>Descrição: </b>{elem['descriÃ§Ã£o']}</p>"
    if ligacoes.get(elem['id']):
        templateCidade += f"<br><h3>Ligações</h3><ul>"
        for id, nome in sorted(ligacoes[elem['id']], key=lambda x: x[1]):
            templateCidade += f"<li><a href='/{id}'>{nome}</a></li>"
    templateCidade += "</ul><br>"
    templateCidade += '''
            </div>
            <footer class="w3-container w3-teal" style="display: flex; justify-content: space-between; padding: 10px">
                <address style="margin-right: auto;">
                        <a href="/">Voltar à página principal</a>
                    </address>
                <span style="margin-left: auto;">Generated by RuasDeBraga::EngWeb2024::A100594</span>
            </footer>
        </div>
    </body>
    </html>
    '''
    fileCidade = open(f"html/{elem['id']}.html", "w", encoding="utf-8")
    fileCidade.write(templateCidade)
    fileCidade.close()



for id, nome in sorted(listaCidades, key=lambda x: x[1]):
    html += f"<li><a href='/{id}'>{nome}</li>"

html += "</ul>"

html += "</body>"
html += "</html>"

file = open("html/index.html", "w", encoding="utf-8")
file.write(html)
file.close()