// Templates Compositores

exports.compositoresListPage = function(clist, plist, d){
    var pagHTML = `
    <!DOCTYPE html>
    <html>
        <head>
            <meta charset="UTF-8"/>
            <link rel="icon" href="favicon.png"/>
            <link rel="stylesheet" href="w3.css"/>
            <title>Compositores</title>
        </head>
        <body>
            <div class="w3-card-4">

                <header class="w3-container w3-teal">
                    <h1>Lista Compositores
                    <a class="w3-btn w3-round w3-grey" href="/compositores/registo">+</a>
                    </h1>
                </header>

                <br>
                <div class="w3-container">
                    <table class="w3-table-all">
                        <tr>
                            <th>Id</th>
                            <th>Nome</th>
                            <th>Periodo</th>
                            <th>Ações</th>
                        </tr>
                `
    for(let i=0; i < clist.length ; i++){
        periodo = null
        for(let j=0; j < plist.length ; j++) {
            if (clist[i].periodo == plist[j].id) {
                periodo = plist[j].nome
            }
        }
        pagHTML += `
                <tr>
                    <td>${clist[i].id}</td>
                    <td><a href="/compositores/${clist[i].id}">${clist[i].nome}</a></td>
                    <td><a href="/periodos/${clist[i].periodo}">${periodo}</a></td>
                    <td>
                        [<a href="/compositores/edit/${clist[i].id}">Edit</a>][<a href="/compositores/delete/${clist[i].id}">Delete</a>]
                    </td>
                </tr>
        `
    }

    pagHTML += `
            </table>
            </div>
            <br>
                <footer class="w3-container w3-blue">
                    <h5>Generated by EngWeb2024 in ${d}</h5>
                </footer>
            </div>
        </body>
    </html>
    `
    return pagHTML
}


exports.compositorFormPage = function(plist, d){
    html = `
    <!DOCTYPE html>
    <html>
        <head>
            <meta charset="UTF-8"/>
            <link rel="icon" href="favicon.png"/>
            <link rel="stylesheet" href="w3.css"/>
            <title>Compositor Form</title>
        </head>
        <body>
            <div class="w3-card-4">
                <header class="w3-container w3-purple">
                    <h2>Compositor Form</h2>
                </header>
            
                <form class="w3-container" method="POST">
                    <fieldset>
                        <legend>Metadata</legend>
                        <br>
                        <label>Id</label>
                        <input class="w3-input w3-round" type="text" name="id"/>
                        <br>
                        <label>Nome</label>
                        <input class="w3-input w3-round" type="text" name="nome"/>
                        <br>
                        <label>Data de Nascimento</label>
                        <input class="w3-input w3-round" type="date" name="dataNasc"/>
                        <br>
                        <label>Data de Óbito</label>
                        <input class="w3-input w3-round" type="date" name="dataObito"/>
                        <br>
                        <label>Período</label>
                        <br>
                        <br>
                        <select class="w3-select w3-round" name="periodo">`

    for (var i = 0; i < plist.length; i++) {
        html += `<option value="${plist[i].id}">${plist[i].nome}</option>`
    }

    html += `           </select>
                        <br>
                        <br>
                        <label>Biografia</label>
                        <textarea class="w3-input w3-round" name="bio"></textarea>
                        <br>
                    </fieldset>
                    <br/>
                    <button class="w3-btn w3-purple w3-mb-2" type="submit">Register</button>
                </form>

                <footer class="w3-container w3-purple">
                    <h5>Generated by EngWeb2024 in ${d} - [<a href="/compositores">Return</a>]</h5>
                </footer>
            
            </div>
    `

    return html
}

exports.compositorFormEditPage = function(a, plist, d){
    var pagHTML = `
    <!DOCTYPE html>
    <html>
        <head>
            <meta charset="UTF-8"/>
            <link rel="icon" href="favicon.png"/>
            <link rel="stylesheet" href="w3.css"/>
            <title>Compositor Form</title>
        </head>
        <body>
            <div class="w3-card-4">
                <header class="w3-container w3-purple">
                    <h2>Compositor Form</h2>
                </header>
            
                <form class="w3-container" method="POST">
                    <fieldset>
                        <legend>Metadata</legend>
                        <label>Id</label>
                        <input class="w3-input w3-round" type="text" name="id" readonly value="${a.id}"/>
                        <br>
                        <label>Nome</label>
                        <input class="w3-input w3-round" type="text" name="nome" value="${a.nome}"/>
                        <br>
                        <label>Data de Nascimento</label>
                        <input class="w3-input w3-round" type="date" name="dataNasc" value="${a.dataNasc}"/>
                        <br>
                        <label>Data de Óbito</label>
                        <input class="w3-input w3-round" type="date" name="dataObito" value="${a.dataObito}"/>
                        <br>
                        <label>Período</label>
                        <br>
                        <br>
                        <select class="w3-select w3-round" name="periodo">`

    for (var i = 0; i < plist.length; i++) {
        if (plist[i].id == a.periodo) {
            pagHTML += `<option value="${plist[i].id}">${plist[i].nome}</option>`
        }
    }
    for (var i = 0; i < plist.length; i++) {
        if (plist[i].id != a.periodo) {
            pagHTML += `<option value="${plist[i].id}">${plist[i].nome}</option>`
        }
    }

    pagHTML += `        </select>
                        <br>
                        <br>
                        <label>Biografia</label>
                        <textarea class="w3-input w3-round" name="bio">${a.bio}</textarea>
                        <br>
                    </fieldset>
                    <br/>
                    <button class="w3-btn w3-purple w3-mb-2" type="submit">Register</button>
                </form>

                <footer class="w3-container w3-purple">
                    <h5>Generated by EngWeb2024 in ${d} - [<a href="/compositores/${a.id}">Return</a>]</h5>
                </footer>
            
            </div>
    `

    return pagHTML
}

exports.compositorPage = function( compositor, periodo, d ){
    var pagHTML = `
    <html>
    <head>
        <title>Compositor: ${compositor.id}</title>
        <meta charset="utf-8"/>
        <link rel="icon" href="favicon.png"/>
        <link rel="stylesheet" href="w3.css"/>
    </head>
    <body>
        <div class="w3-card-4">
            <header class="w3-container w3-teal">
                <h1>Compositor ${compositor.id}</h1>
            </header>

            <br>
            <div class="w3-container">
                <ul class="w3-ul w3-card-4" style="width:50%">
                    <li><b>Id: </b> ${compositor.id}</li>
                    <li><b>Nome: </b> ${compositor.nome}</li>
                    <li><b>Data de Nascimento: </b> ${compositor.dataNasc}</li>
                    <li><b>Data de Óbito: </b> ${compositor.dataObito}</li>
                    <li><b>Período: </b><a href="/periodos/${compositor.periodo}">${periodo.nome}</a></li>
                    <li><p>${compositor.bio}</p></li>
                </ul>
            </div>
            <br>`

    pagHTML += `
            <footer class="w3-container w3-teal">
                <address>Gerado por galuno::EngWeb2024 em ${d} - [<a href="/compositores">Voltar</a>]</address>
            </footer>
        </div>
    </body>
    </html>
    `
    return pagHTML
}

// -------------- Error Treatment ------------------------------
exports.errorPage = function(errorMessage, d){
    return `
    <html>
    <head>
        <title>Error page</title>
        <meta charset="utf-8"/>
        <link rel="icon" href="favicon.png"/>
        <link rel="stylesheet" href="w3.css"/>
    </head>
    <body>
        <div class="w3-card-4">
            <header class="w3-container w3-teal">
                <h1>Error page</h1>
            </header>
            <div class="w3-container">
                <p>${errorMessage}</p>
            </div>
            <footer class="w3-container w3-teal">
                <address>Generated by EngWeb2024 in ${d} - [<a href="/compositores">Voltar</a>]</address>
            </footer>
        </div>
    </body>
    </html>
    `
}




// Templates Periodos

exports.periodosListPage = function(plist, d){
    var pagHTML = `
    <!DOCTYPE html>
    <html>
        <head>
            <meta charset="UTF-8"/>
            <link rel="icon" href="favicon.png"/>
            <link rel="stylesheet" href="w3.css"/>
            <title>Periodos</title>
        </head>
        <body>
            <div class="w3-card-4">

                <header class="w3-container w3-teal">
                    <h1>Lista Periodos
                    <a class="w3-btn w3-round w3-grey" href="/periodos/registo">+</a>
                    </h1>
                </header>
        
                <br>
                <div class="w3-container">
                    <table class="w3-table-all">
                        <tr>
                            <th>Nome</th>
                            <th>Ações</th>
                        </tr>
                `
    for(let i=0; i < plist.length ; i++){
        pagHTML += `
                <tr>
                    <td><a href="/periodos/${plist[i].id}">${plist[i].nome}</a></td>
                    <td>
                        [<a href="/periodos/edit/${plist[i].id}">Edit</a>][<a href="/periodos/delete/${plist[i].id}">Delete</a>]
                    </td>
                </tr>
        `
    }

    pagHTML += `
            </table>
            </div>
            <br>
                <footer class="w3-container w3-blue">
                    <h5>Generated by EngWeb2024 in ${d}</h5>
                </footer>
            </div>
        </body>
    </html>
    `
    return pagHTML
}


exports.periodoFormPage = function(plist, d){
    html = `
    <!DOCTYPE html>
    <html>
        <head>
            <meta charset="UTF-8"/>
            <link rel="icon" href="favicon.png"/>
            <link rel="stylesheet" href="w3.css"/>
            <title>Compositor Form</title>
        </head>
        <body>
            <div class="w3-card-4">
                <header class="w3-container w3-purple">
                    <h2>Compositor Form</h2>
                </header>
            
                <br/>
                <form class="w3-container" method="POST">
                    <fieldset>
                        <legend>Metadata</legend>
                        <br>
                        <label>Nome</label>
                        <input class="w3-input w3-round" type="text" name="nome"/>
                    </fieldset>
                    <br/>
                    <button class="w3-btn w3-purple w3-mb-2" type="submit">Register</button>
                </form>
                <br/>

                <footer class="w3-container w3-purple">
                    <h5>Generated by EngWeb2024 in ${d} - [<a href="/periodos">Return</a>]</h5>
                </footer>
            
            </div>
    `

    return html
}

exports.periodoFormEditPage = function(a, d){
    var pagHTML = `
    <!DOCTYPE html>
    <html>
        <head>
            <meta charset="UTF-8"/>
            <link rel="icon" href="favicon.png"/>
            <link rel="stylesheet" href="w3.css"/>
            <title>Periodo Form</title>
        </head>
        <body>
            <div class="w3-card-4">
                <header class="w3-container w3-purple">
                    <h2>Periodo Form</h2>
                </header>
            
                <br/>
                <form class="w3-container" method="POST">
                    <fieldset>
                        <legend>Metadata</legend>
                        <br/>
                        <label>Id</label>
                        <input class="w3-input w3-round" type="text" name="id" readonly value="${a.id}"/>
                        <br/>
                        <label>Nome</label>
                        <input class="w3-input w3-round" type="text" name="nome" value="${a.nome}"/>
                    </fieldset>
                    <br/>
                    <button class="w3-btn w3-purple w3-mb-2" type="submit">Register</button>
                </form>
                <br/>

                <footer class="w3-container w3-purple">
                    <h5>Generated by EngWeb2024 in ${d} - [<a href="/periodos/${a.id}">Return</a>]</h5>
                </footer>
            
            </div>
    `

    return pagHTML
}

exports.periodoPage = function( periodo, clist, d ){
    var pagHTML = `
    <html>
    <head>
        <title>Periodo: ${periodo.nome}</title>
        <meta charset="utf-8"/>
        <link rel="icon" href="favicon.png"/>
        <link rel="stylesheet" href="w3.css"/>
    </head>
    <body>
        <div class="w3-card-4">
            <header class="w3-container w3-teal">
                <h1>Periodo ${periodo.nome}</h1>
            </header>

            <br>
                <div class="w3-container">
                    <table class="w3-table-all">
                        <tr>
                            <th>Id</th>
                            <th>Nome</th>
                            <th>Data de Nascimento</th>
                            <th>Data de Óbito</th>
                        </tr>
                `
    for(let i=0; i < clist.length ; i++){
        pagHTML += `
                <tr>
                    <td>${clist[i].id}</td>
                    <td><a href="/compositores/${clist[i].id}">${clist[i].nome}</a></td>
                    <td>${clist[i].dataNasc}</td>
                    <td>${clist[i].dataObito}</td>
                </tr>
        `
    }

    pagHTML += `
            </table>
            </div>
            <br>
                <footer class="w3-container w3-blue">
                <address>Gerado por galuno::EngWeb2024 em ${d} - [<a href="/periodos">Voltar</a>]</address>
                </footer>
            </div>
        </body>
    </html>
    `
    return pagHTML
}

// -------------- Error Treatment ------------------------------
exports.errorPagePeriodos = function(errorMessage, d){
    return `
    <html>
    <head>
        <title>Error page</title>
        <meta charset="utf-8"/>
        <link rel="icon" href="favicon.png"/>
        <link rel="stylesheet" href="w3.css"/>
    </head>
    <body>
        <div class="w3-card-4">
            <header class="w3-container w3-teal">
                <h1>Error page</h1>
            </header>
            <div class="w3-container">
                <p>${errorMessage}</p>
            </div>
            <footer class="w3-container w3-teal">
                <address>Generated by EngWeb2024 in ${d} - [<a href="/periodos">Voltar</a>]</address>
            </footer>
        </div>
    </body>
    </html>
    `
}