import os
import shutil
import xml.etree.ElementTree as ET

html = '''
<!DOCTYPE html>
<html>
<head>
    <title>{title}</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
</head>
<body>
'''

html_folder = 'html'
if os.path.exists(html_folder):
    shutil.rmtree(html_folder)
os.makedirs(html_folder)

main = html

def get_xml_info(xml_file):
    tree = ET.parse(xml_file)
    root = tree.getroot()

    meta = root.find('meta')
    numero = meta.find('número').text
    nome = meta.find('nome').text

    content = html
    content += '''
        <div class="w3-card-4">
            <header class="w3-container w3-teal">
                <h3>{name_street}</h3>
            </header>
            <div class="w3-container">
    '''
    content = content.format(title=f"{nome}", name_street=nome)

    corpo = root.find('corpo')
    figuras = corpo.findall('figura')

    i = 1
    for figura in figuras:
        imagem_path = figura.find('imagem').attrib['path'].replace("../", "")
        legenda = figura.find('legenda').text
        content += f"<div style='text-align: center;'><figure><img src='{'../Dados/MapaRuas-materialBase/' + imagem_path}' style='max-width: 80%;height: auto;' alt='{legenda}'><figcaption style='font-size: 14px;'>Fig. {i} - {legenda}</figcaption></figure></div>"
        i += 1
    content += "<br>"

    for para_element in corpo.findall('para'):
        content += f"<p>{ET.tostring(para_element, method='text', encoding='unicode')}</p>"

    lista_casas = corpo.find('lista-casas')
    if lista_casas is not None:
        content += "<ul><br>"
        for casa in lista_casas.findall('casa'):
            numero_casa = casa.find('número').text
            enfiteuta = casa.find('enfiteuta')
            enfiteuta_text = enfiteuta.text if enfiteuta is not None and enfiteuta.text is not None else "Não existe enfiteuta"
            foro = casa.find('foro')
            foro_text = foro.text if foro is not None and foro.text is not None else "Não existe foro"
            desc = casa.find('desc')
            desc_text = ET.tostring(desc, method='text', encoding='unicode').strip() if desc is not None else ""
            content += f"<li>Casa número {numero_casa}<br>Enfiteuta: {enfiteuta_text}<br>Foro: {foro_text}<br>Descrição: {desc_text}</li><br>"
        content += "</ul><br>"
    
    content += '''
            </div>
            <footer class="w3-container w3-teal" style="display: flex; justify-content: space-between; padding: 10px">
                <address style="margin-right: auto;">
                        <a href="../html/index.html">Voltar à página principal</a>
                    </address>
                <span style="margin-left: auto;">Generated by RuasDeBraga::EngWeb2024::A100594</span>
            </footer>
        </div>
    </body>
    </html>
    '''
    
    file = open(f"html/{nome}.html", "w", encoding="utf-8")
    file.write(content)
    file.close()

    return nome


nomes_ruas = []
for xml_file in os.listdir("Dados/MapaRuas-materialBase/texto"):
    if xml_file.endswith('.xml'):
        nomes_ruas.append(get_xml_info(os.path.join("Dados/MapaRuas-materialBase/texto", xml_file)))

main += '''
    <div class="w3-card-4">
        <header class="w3-container w3-teal">
            <h3>Ruas de Braga</h3>
        </header>
        <div class="w3-container">
            <ul>
'''
for nome in sorted(nomes_ruas):
    main += f"<li><a href='../html/{nome}.html'>{nome}</a></li>"

main += '''
        </ul>
        </div>
        <footer class="w3-container w3-teal">
            <h6>Generated by RuasDeBraga::EngWeb2024::A100594</h6>
        </footer>
    </div>
</body>
</html>
'''

main = main.format(title=f"Ruas de Braga")

file = open("html/index.html", "w", encoding="utf-8")
file.write(main)
file.close()
